apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:+esZU5aj7M8dHcCiAC+f+p0X8erCPLhkub8TW53yH9jlIa7Bhrl6Cg==,iv:x59u+WoMSIpWUJ96M88wwjoPfq2yhSjWZn4VAFQUA88=,tag:SFdiy/ns8O3flOU8z2EidA==,type:str]
sops:
  age:
    - recipient: age1txas6eje7zhjxfytqwgsxflnjaca8c5xm745ngfynz8lrdtjd3aqh0fr9a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaVF5Qk9waXVxa0FzdWFv
        b0Q3UG1GaGdZbVRyRHJkSi8wbStoMFpjTUdFCm5tMnZEOGlGLzhaMGFsMHdKb0JI
        d05XdVZWb3I5cndHeU5mbjRDa1I3czQKLS0tIGg0MTVjK2FhQWZTeDZvb1pNRjJw
        eFBhK3RKN2hDNmlSZVNNWHZvMHhmK0UKTFSgZZvomZ+VsSlcj2FRNhPrv2A/4vql
        3Dhq9GHBsqiJFu5LKWI3FJgSelpn0AkjPCfYRDq2vH1EAMyOapzTbw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T20:02:32Z"
  mac: ENC[AES256_GCM,data:xjMwqn0t93CCRUic9wvvN3TciEqd267+D7wC4YpHsUbSPiXjZUH4xfxAG4uWl0BfPkrarQVLrtMYIZKBkXYFmdgEJ90MAIhNcPp7/E2vlwWnbL0aVwLYL2uGPSdhfGW5OIjLCM/2vuo9pAL/XGULZb9udnl2HHtmzM7p0lOD/BY=,iv:w/mfxwbo3oH0LSlIWMBA3RhJN0lhcDFsrTtNT54FbvE=,tag:7PZp7JwzxCkqMhLUIZdf/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
