apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:fxYmGsDF7Mbyi91WLeVo1ASXIN/ccDczLnFqgxXeM3eXQ04ttA3v7w==,iv:MOvOc+2kpam+1RZ1HyEcM8g/9uvDkp1V+dMjMO7HXss=,tag:Xd+yPE62HzGs9c241Y+KvQ==,type:str]
sops:
  age:
    - recipient: age1txas6eje7zhjxfytqwgsxflnjaca8c5xm745ngfynz8lrdtjd3aqh0fr9a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdkpobitVWld6Nm4rR0JS
        MklvK3kvRGY0Mk1kR1E2VW5namNEZGtXcEZVCmV0WGZlWVVYbUVFSm4xaU9nTzhR
        dEhpR1FmcURiMGpWcW1iRDFJcUJjTEEKLS0tIDM3WjMzOEJXdG80SENaS3U2cFlF
        MGF4MUkyMFRJY29TYWtONW5ocmlJTDgKLljBjHckbm0eipbxerwP7+YsyMA2YBcr
        VSpwOpVdtkBPIo11jwmQ5lnSNCEKtAYQ1WnZJlESwBm+CfvpUCdyRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T21:52:07Z"
  mac: ENC[AES256_GCM,data:yUijOJ2V+fLLwrtvUTHgmYeMESwEWop+h2U/FyIvE27cR8J+2rpHMQb+8K8YHPJ7QK7cxnyqAGfoBUO4l/q0k2XAyKmbUi8v4k5M4BZjfbX1SLTYcN1vSFd77r3KwmSz/mSWycMNKPVi22/mPx7TAQHw0vRrF82e3/whXMoaJb0=,iv:HF14/Q6WVW8dLkbbqPoe56ne0vLeTrhv0Iv25ZalYYI=,tag:DKPwvN0QFlqzczhK0sBWvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
