apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:6dvcNRWqj/OJ,iv:TiOTsRp9VQh9NUs5ITyCt0zgYaexisW9LEPaS1QFexc=,tag:9y2Sz54AyGRXPD/VDml3hA==,type:str]
sops:
  age:
    - recipient: age1txas6eje7zhjxfytqwgsxflnjaca8c5xm745ngfynz8lrdtjd3aqh0fr9a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QmpGcEl3SXV4SEVneXJo
        eGxPU2FuZGF3bmd5YXhrV2paSUpuNm5ydkZRCnNuY25Rc2o2NGhjazg0eklISnRr
        ajVpc2VpajBFdFV4VEVPdFdLSno5L1EKLS0tIFFqWXBoazRCaVFDVWIxUVRFaXNr
        UVZmVmwrUTBDNXduNVR0dmNzUmc5clUKMPMQ9D+1ddaToPu5mieed1naSeUmw7Uo
        jL4fnFKchHStYXs6cwZJOGG7J15EgdXgslM+u/7cDlpbPJa+8Akijg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T20:02:32Z"
  mac: ENC[AES256_GCM,data:AsqWiDCuhiyidlGy13hYOuws3bxJetxqbuZ9Yj+eWNXW3TkkOlvee0LjbLdYLvp82xW/ODZ81ZxqbQgzvOOmAwTzjftNKmsqFjuaJ/hmWx6toXtfEaoYF7vKoruJVcGMJ5RI6WI57huTsMlfi0Y8OOxqhQBAubgKiHIvXr2Szi0=,iv:CmLDaVwIlrSIF7xuULUDwv/nXJSyVDwROSJxeEs8iFg=,tag:1e8MNi9tI+KBdiyGfZVsrQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
