apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:AaBaGravIjYP,iv:0PcA9rqJ6ZueddX3IeOA9Gz+Sp6xH+LXXFXbHPs2aSE=,tag:t1jH1Ntq9dHYmPz9yoIjfQ==,type:str]
sops:
  age:
    - recipient: age1txas6eje7zhjxfytqwgsxflnjaca8c5xm745ngfynz8lrdtjd3aqh0fr9a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSkFDZnh6a08vejdETGZZ
        dnN1VmR1RlJVTnRydm5yYWdEQW5uOXNkVkZFCmdsYllGMEVUek90NEpDVHBOMWFZ
        MkZldjFIcitSOThLSzBjNVNMb0pNOUUKLS0tIHBiMW5JeVVTaHVBY2R0aGdwN1RN
        aDM3QkNNcWVDR3lmM1VlMnVpQll0NjAKFoHy+vLbhZIjWDe10xlVdoe6vuBvpf90
        PBL5yv3nRBBMxLzB98e3/+G6ouwZ4KuoChB5stuTWv2OW/+ruZf12g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T21:52:07Z"
  mac: ENC[AES256_GCM,data:B+vV+A7hi/nyNYHCfYXuJSP+CFIN0xQNzmS2mqFxOKhMEgKCaYgCcz7JbT1NDstyqQHA4OryDBKlHmMXsAzfo+OhFknqOW1QbLidZHBc3E2H3jZfSCF1eDUL/e5ZkpkNCgzXXEF2CdkwAzwqetn4jGAEkVVDsRlCqVyL8A56uOE=,iv:bApTgDlmCZzWIbB70k3QqlZOYHm1pGugUDSHtx1ESZo=,tag:5IsPWK5OYYo9Roq1fnM58Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
