apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:6Si4MD1vQIR5FF5C5NU3fpillf+d5WFs1/9X3pyqlpE=,iv:MthV8NJw+EWOXYhfMv4iRmFI7HOAPqlwOufOVjP//Do=,tag:830gq0s07Yh9cyzNkqzGqA==,type:str]
sops:
  age:
    - recipient: age1txas6eje7zhjxfytqwgsxflnjaca8c5xm745ngfynz8lrdtjd3aqh0fr9a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZFdZdXEzekZiUERMRDZ3
        Z2VFSHh5dW5hTXFPK0J5eElGYzZERVkrcG5rClVENUp1d3lQbVJQNFd1ZU1yK2VI
        NGE1eXJHbU8rakU5aTl2ZUJDNk11YmsKLS0tIGU3cHE2UHZ4ZzhmbHlkZ29XYWgx
        YlZTYk1QOUxKL0NDR0xud3NZcTFqaTgKrsnWBb6YpG0r9CcvAQ12dYlmVTRVZ9/y
        xzh4vej64sxqQNyjr/sXqdRfuloGk+X67B+hBdHa5ZR0FqBO5rS3Gw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T21:52:07Z"
  mac: ENC[AES256_GCM,data:1ze24tPsVCVBdzbz8vpYHM+rdGsqLQODN7MRWUv61+ZxMXK1MGwSm6XGZOUk45UBYFRy3j5NfE75J+GrqEO2ybYbGGf5VyghTF0Irxq1OHAg+xwwh5ApNerizsqPQh5fEyGK8NQq6G/pWIsr6zR6qNw65ztORB8dOsJrtyZgwFw=,iv:vO4VEska0T3VPDDNic/UCmagPG0FRjVYRilwf5T0ZWY=,tag:2q6iedtb49g1rmp04Q8xow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
