apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:d7ZGRxlQqCQSkNeXppzSSgYtw0ciqSVLN1Q9IGAOutA=,iv:6AuKIPCbnmmyl2WlQp5jmCLBccZJ9JRbFkC/hW5tpi4=,tag:GKcDtyW9YV+U/jH3IQMoMQ==,type:str]
sops:
  age:
    - recipient: age1txas6eje7zhjxfytqwgsxflnjaca8c5xm745ngfynz8lrdtjd3aqh0fr9a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZXIwckFpZnJxNElVK01F
        NDgxSDRqZXhlQ3N5VFFsR2JQK2NkT2hWL0Y0CjFzSEpwMVNQVVBXRDdIZWxUY0gv
        a3VHelppMlc4RXhpVjVadENSaFpFeDAKLS0tIC9OaXVyMTZ3di9rdkhUNWUxSk9Q
        cnIxV3NtZEhMdXZ5OXpzZXVxQjF1WVkKF40hHWH1MtBopfO+w8QmmjmDHPFd45Dh
        hj1dqcyCNx8+gwhdBqieYk5zYDLEWopo9/JCncJedAceelbD5DPizg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T20:02:32Z"
  mac: ENC[AES256_GCM,data:94Yad7hS8I2mmEUkxdegekyFgrB+v1pWZsH0eCiXYzVxdQz1C/JvwSz6qQKZ2BjyxVOBY3JXuptQ5x5/1vMakRUaOl+MKnMnIgRS9UEymjqSJ9GEd9K3Finvc2cKBylTuU/TNA2FlcDgLCunIvSWvUdu8tFVsWnFYqlQuXPzjQY=,iv:UWBUiNLbpwEHrX0HEJDvRbr6yIaxqTQ7muYx+m/4/HU=,tag:z462YKRYJ/z7hiac0ofhKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
