apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:zDLpYIFasQTCTeXZb13QRuBLCIi+s0pxq0kVZvm8k8sSBbi3l/OuJpS5wpv9kwoX016BvNvj0doOnb6XTO1enapnlUUc0utlAx+R0+Avfd0nlTVFX1ibjXSq34f1O52ufa3/DXnxGqAR8X/o6dYu7GsTQJp8uPXBlmJjtcf/R27SDy2JtsqoG9bb2nU1dFLs22pqdrb6Z22NmhvZXbAIatAAIIJONwMACRaznXQPdu52n0Os,iv:JRHaADNkTSn9D9iWj3bp89/n+ghs8KSotGEGnkPRC0k=,tag:hpwTLBF73NM1XmiH9OpMjg==,type:str]
sops:
  age:
    - recipient: age1txas6eje7zhjxfytqwgsxflnjaca8c5xm745ngfynz8lrdtjd3aqh0fr9a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZG8xK0JUNElkTVNKNXhI
        TXdQNlhVVXdhd0thTzI2Wk9yRzJwaXQvQVRRClFCUE02NUVuVnpNMVZVZTFuekFC
        SVJ1VGNCaWRLK2dxZi9PajhSWVR5TEkKLS0tIGxSYUVLdEhINzJPb2F1QnRnbi9V
        dmlhNnN1bnVaNVorYVNNeTZ5TEl4R2sKCZE8Kh4vftDNJXOY5ZIiRfZpS1lfFRGT
        g/YmduX4lEenQ5tYECbvidJqjit4fjAy75oombxXpUQ4exq92oO1/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T21:52:07Z"
  mac: ENC[AES256_GCM,data:MIgjArCkxLrUfpl2wKYuoo1XypCLiHRE4rdoslEFXWHv9DxG8fjd2bWdwrSKcIMU9N8DbGjx3jUaurk0AKgwConH0YNTA24fZuzSS+CmxeTvsdDo0J+ONd4/8D7s/25YcquUEQjHEJIhXJujsD3IDeUambJf/N0L8fMkXfaEJFk=,iv:0eSh8m8nQTVbWYM/PoVFLlHoBbtNHnmf28nxZCD7c0Y=,tag:/I77w2G2GePFFhVrru50HQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
