apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:oSWi4aYNd4bNrctfkKqjLeA+syvhU0dDST/dWeWRCL6SXNTK21gEVZ8iHdMMcBs9lAg22ck4q+QoZsubIdH1EXOz+ELpzXBSRFDltnNdSXhOmqr6D22Zz9ablI1JCBQRjTlHpiaQRxSlDXp/kXZ3ScOlAzW9woI+oMNOOBjwaCcwf2QtOmZz0hXErqFAV4DWpMwK141fWYAJhPRbb/E5sU/n3y0O4UfdmurziSEaGz3wNXyI,iv:LpKSgQciEw6g3lEZ1mKG9oytgdgDpR2kzo/j+CcWAr8=,tag:SxelUTbBT0ztdR/oRMy/lw==,type:str]
sops:
  age:
    - recipient: age1txas6eje7zhjxfytqwgsxflnjaca8c5xm745ngfynz8lrdtjd3aqh0fr9a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISDVIQXQvYmF5YkJOaWRV
        d1FrczdQelkwMjZ6b3AzeFp1S0lFUzVmakZFCmU0RnkxR0U5R052b2ZKa0pINkFz
        MzhnVjg3enVKZTFwYkdvcDhlalZJV00KLS0tIG1ibVh6L0JoTElKWUZWUjBzcjU3
        eGtNRkxoRDhEMlJvTmFyRnFpZTZDd3cKkY6tdudUqubDli+ojRbSAW7uYsPiZ05a
        miqFu0noe/Zck4x/GmHvp1fA8COPZXV/CJ3LdgLih7hfHah2utbR9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T20:02:32Z"
  mac: ENC[AES256_GCM,data:FXWZBMz2JfHk6tU9vxJeKVyzdH3XjO8+KHusXj5B6vCEOzhHBdALf0LcI8Az7BzWrpk/rkNTEnSshLAL6Ta98KMrdgrmBdasA+pdoVvq+oi3CNCXezb4rcl02PQfPQejjREP2ZSFZncMppz1b2JXnMvNaxsAGwMUNxh6jdMCqTw=,iv:O9S+RRIB4AjvC/PmHMM6QNnND317OcrMVV8X8NCNOwU=,tag:Nlidb678oN/Rl3O5FEGJ1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
