apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:dSDMvIVrkQNnDAs7vRh96FteFIB0PQvVD8R6jNnMtRfg9ckuU2HzOA==,iv:sO/I74Xn5Ur47PwLeOIE8TIQ3X0Zpmx8bpxvhOultnU=,tag:HCU7JJaRU6gE3ghbhUtgaw==,type:str]
sops:
  age:
    - recipient: age1txas6eje7zhjxfytqwgsxflnjaca8c5xm745ngfynz8lrdtjd3aqh0fr9a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WWx1RE1DeTNBMis2VTRW
        R1JZU0xIY1p5bVpRem8xanRXaDg5VEQwcFNzCmtVTkthLzF0T1RTMFhFVWl6QU5E
        aUJuVTlmbGF5WlVxSkxXZlA4Z3ZndGMKLS0tIEpTbWJ5ejRsS0s1L2xSTDBNNlJS
        MG1MaWN1dUZwYkFEVE01dTVXUjFZdWMKWcXqIA6YTh5lyoyXKBrkcuzBL6RpFTWG
        gcHN91RFzTmzgTIDqEpf25EGohwbY2mi8UlTBAAGgxvlT2NgiAv0lA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T20:02:32Z"
  mac: ENC[AES256_GCM,data:VoTCWa5YbklsR2iM7ev/e+HFfae4wTH4iWvYpfOA8NnDyaiGHBH38vMzN1VySNFUQR9St5rnBRgXJ30Q7PzyOqulNw9I+u6QEfc/fe8LOVPolxMCnvtYEbrGl48pvrs82Ff1Rnf0BBTIaFg/OThxT/SdsTrz+mRw8vsdnJEpfVc=,iv:0/e9jBeJB7hcgP31B9mXKLGPzZofHK1CgXWGWxaRfk0=,tag:ZuPXpY3wb2gk0K9OHGjHWQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
