apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:BDt9CNhQk6MD/yCtTLDwPm9Dl3DzjtLUVhbAYCIPeLgLQW6Gx+cNoA==,iv:AG9oRXebAPdtwpXi+oky8I64/FVGFp7u3sZcAKnv6OA=,tag:jYZAmzhFb3pkyOs6U66k7w==,type:str]
sops:
  age:
    - recipient: age1txas6eje7zhjxfytqwgsxflnjaca8c5xm745ngfynz8lrdtjd3aqh0fr9a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraDNXYzgyTnpKUWNVWEo0
        SVR4K1NtMUhwYUdJc0hnZUluVkpwQ2YveXlnCjRpT21kQnJyS1JGN2cyb01SWUtV
        Z3B3UlBQcEJCZjB2SzhFdGJYSUtHTk0KLS0tIFp3d0ZDaWNrRlFmMFROMWEzV09V
        NFBickQ1amJwdHlOY1NsVHBDakFGMmMKqhete8lMzQ49ASy9pEHUpapMJrfe2d+w
        FlwndJ/uF73BZ8/F4oB0epAGEY0UU2mEvJDFS3ig/zFLVOjIHYkcDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T21:52:07Z"
  mac: ENC[AES256_GCM,data:4KzpdYfVqos1jI9hAgcE6kdQhF2OBm8sOAxwNqXcIumukyuDuCpeve4T98zIAujZEmeZtOY75MYGiQf4eAl2dDuyn+ooXpRtcJhDdb8w6O9WkxV+PQOug0eehf19XeP+/dzINGP4jJkP6EP0AyZog7fh9Qwcn05Kkk6gq2qHoQo=,iv:GpbivZ3M/jVRs6Hog6oJfaR3OJpuJLwNa5NDElLOs+E=,tag:cEmIOF9cmTlcDbjey1VhGQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
