---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://172.16.69.57:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "172.16.69.57"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-cp-01"
    ipAddress: "172.16.69.61"
    installDiskSelector:
      serial: "naa.57c3548257bf295e"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/4b3cd373a192c8469e859b7a0cfbed3ecc3577c4a2d346a37b0aeff9cd17cdb0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "48:21:0b:35:a3:c7"
        dhcp: false
        addresses:
          - "172.16.69.61/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "172.16.69.1"
        mtu: 1500
        vip:
          ip: "172.16.69.57"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

